---
title: Software
---

# Sonobuoy Codes

*This part will most likely move elsewhere with just the code living here, but this is easier for my brain at the moment*

1.  You will need to make sure you have named the deployment folder and files correctly. It's better to have it right before you start recording, but this can be fixed afterwards. These will be in the same format as the moorings, towed arrays, dipping phones, saildrones, etc.

<!-- -->

a)  Deployment folder will be in the format: ***PPXX_SB_CCLL***, where:

-   PP is project code (e.g., POWER = PW; CHAOZ = CZ; Haida Gwaii = HG; ALTIMA = AL)\
    (I will make a list that lives here, or is linked to Google drive folder; for the moment verify with Crance or Berchok).
-   XX is the 2 digit year
-   SB is sonobuoy
-   CC is the Vessel name (e.g., AQ = Aquila, DY = Dyson, YM = Yushin Maru)
-   LL is the cruise leg (if you just have 1 big leg, then the whole thing is just 01).
-   Underscores are important here
-   Examples: PW24_SB_YM01, HG24_SB_TU01, CZ14_SB_AQ02, BC24_SB_AS01

b)  Once you have the Deployment Folder name, the files follow the same codes just in a slightly different order:

-   ***SB-PPCCLL-YYMMDD-HHMMSS.wav***, where - YYMMDD-HHMMSS is the year, month, day, 24hour, minute, second **local** field time. - Dashes are important here. - Examples: SB-PWYM01-240813-182113.wav, SB-HGTU01-240528-211538.wav

2.  A drive data: Back up the data in 2 places:

-   An A drive
-   A SB Backup drive
-   Both these locations should have all the wave files + all the .mat files from BoatTrackPosns and SONOstationPosns + the sonoExcel file.
-   Once you have made sure the same number of files are in all places, you can delete the files from your field drives.
-   Also make a new row in the Where the files are excel here: ADD LINK TO GOOGLE DRIVE, and note the A and SB backup drive numbers.

## Sonobuoy Raw to B drive conversion process

*(You have come back from sea and have successfully collected sonobuoy data, now what?)*

**Things you'll need:**

```         
- Correctly named project folder and files
- Fully completed recording log
- Matlab version 2023b or higher (maybe 2023a will work)
- SonoRename_v1.m code
```

-   You can change the pathing in lines 11, 13, and 15 of the code, or you can just browse to the folders while running code.

1.  You will first point to the folder that contains your raw wave files.
2.  Then you will point to a fast external drive (just the drive letter).
3.  Then you need to choose which location the sonobuoy recordings were deployed in (Matlab can handle the time zone and daylight savings business). If one is missing, let CB know.\

```{=html}
<!-- -->
```
a)  But the way to add is typing *timezones* into the command window to get the table, then you add that info in the tz= line (around line 20) of the code. If you alter the code, please be sure to make a backup following that procedure.
